### ISSUE TITLE
Hello, I made an error while using it

### ISSUE THREAD

**Issue by aidyHe** [misha130/ionic2-select-nobuttons#1]
No value accessor for form control with name:periodCode
`<select-alertless item-content formControlName="periodCode"  >
                <ion-option>First</ion-option>
                <ion-option>Second</ion-option>
                <ion-option>Third</ion-option>
            </select-alertless>`

**Comment by misha130** [comment]
Ionic team rebuilt a bunch of things in their 3.4 version so I had to rebuild the class again.
If you take the class now it should work.

**Comment by aidyHe** [comment]
Hello, I've solved the problem. Your component has no problem. It was caused by my improper use. And looking forward to your continuous update. You are great, thank you
